<?php
$this->title = "Change your password";
$this->headTitle($this->title);
echo $this->form;
?>
<p>Are you sure that you want to change your password
'<?php echo $this->escape($this->users['pass']); ?>'?
</p>
<form action="<?php echo $this->url(array('action'=>'delete')); ?>" method="post">
<div>
<input type="hidden" name="id" value="<?php echo $this->users['id']; ?>" />
<input type="submit" name="del" value="Yes" />
<input type="submit" name="del" value="No" />
</div>
</form>

