<script>
    $(function() {
        var dates = $( "#from, #to" ).datepicker({
            defaultDate: "-1w",
            changeMonth: true,
            numberOfMonths: 2,
            onSelect: function( selectedDate ) {
                var option = this.id == "from" ? "minDate" : "maxDate",
                instance = $( this ).data( "datepicker" ),
                date = $.datepicker.parseDate(
                instance.settings.dateFormat ||
                    $.datepicker._defaults.dateFormat,
                selectedDate, instance.settings );
                dates.not( this ).datepicker( "option", option, date );
            }
        });
    });
</script>

<div class="greyBox" float="left">
    <div class="greyBoxTitle"><?php echo $this->translate('Create report for Users'); ?></div>

    <?php
    echo $this->form;
    echo '</div>';
    ?>


    <div class="greyBox2">
    <div class="greyBoxTitle"><?php echo $this->translate('Show saved report from history'); ?></div>
        <ul>
        <?php foreach ($this->reportList as $report) { ?>

            <li> ID: <?php echo $report->reportId; ?> :: <?php echo $this->translate('Created'); ?> <?php echo $report->createDate; ?> <?php echo $this->translate('by'); ?> <?php echo $report->login; ?> &raquo; <a href="<?php echo $this->url( array('module'=>'support','controller'=>'stat','action'=>'users','report'=>$report->reportId) ); ?>"> <?php echo $this->translate('show'); ?> </a> </li>

        <?php } ?>
        </ul>
    </div>

    <?php
    $this->jQuery()->enable()->uiEnable();
    if ($this->report) {
    ?>

        <script type="text/javascript" charset="utf-8">
            $(document).ready(function() {
                $('#expertReport').dataTable( {
                    "bJQueryUI": true,
                    "bAutoWidth": true
                } );
            } );
        </script>

    <?php $id = 0; ?>

        <br style="clear:both"/>

        <h3>Your report:  </h3>

        <?php

        echo $this->formRaport;

        ?>

        <table id="expertReport">
            <thead>
                <tr>
                    <th style="width:28%"><?php echo $this->translate('Username'); ?></th>
                    <th style="width:8%"><?php echo $this->translate('ClientCreate'); ?></th>
                    <th style="width:8%"><?php echo $this->translate('ClientComment'); ?></th>
                    <th style="width:8%"><?php echo $this->translate('Create'); ?></th>
                    <th style="width:8%"><?php echo $this->translate('Close'); ?></th>
                    <th style="width:8%"><?php echo $this->translate('Comment'); ?></th>
                    <th style="width:8%"><?php echo $this->translate('Get'); ?></th>
                    <th style="width:8%"><?php echo $this->translate('CreateSRQ'); ?></th>
                    <th style="width:8%"><?php echo $this->translate('Priority'); ?></th>
                    <th style="width:8%"><?php echo $this->translate('Category'); ?></th>
                </tr>
            </thead>
            <tbody>
            <?php foreach ($this->results as $users) : ?>
                <tr style="text-align: center;">
                    <td><?php echo $this->escape($users->login); ?></td>
                    <td><?php echo $this->escape($users->createClient); ?></td>
                    <td><?php echo $this->escape($users->commentClient); ?></td>
                    <td><?php echo $this->escape($users->create); ?></td>
                    <td><?php echo $this->escape($users->close); ?></td>
                    <td><?php echo $this->escape($users->comment); ?></td>
                    <td><?php echo $this->escape($users->get); ?></td>
                    <td><?php echo $this->escape($users->createSRQ); ?></td>
                    <td><?php echo $this->escape($users->priority); ?></td>
                    <td><?php echo $this->escape($users->category); ?></td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>

    <?php
            }
    ?>