<?php
$this->title = "Premissions";
$this->headTitle($this->title);
$this->jQuery()->enable();
?>

<script type="text/javascript" charset="utf-8">
    $(document).ready(function() {
        $('#premissionList').dataTable( {
            "bJQueryUI": true,
            "bAutoWidth": true
        } );
    } );
</script>

<?php $id = 0; ?>

<div style="width:50%;overflow:hidden">
    <table id="premissionList">
        <thead>
            <tr>
                <th style="width:10%">Id</th>
                <th style="width:160%"><?php echo $this->translate('Username'); ?></th>
                <th style="width:20%"><?php echo $this->translate('Edit'); ?></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->experts as $expert) : ?>
                <tr<?php if ($id % 2 == 0)
                    echo ' class="grey" '; $id++; ?>>
                    <td style="padding:7px;"><?php echo $this->escape($expert->id); ?></td>
                <td><?php echo $this->escape($expert->login); ?></td>
                <td style="text-align: center">
                    <a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'user', 'action' => 'editpremissions', 'id' => $expert->id), 'default'); ?>">
                        <img src="<?php echo $this->baseUrl(); ?>/css/img/edit.gif" alt="" />
                    </a>
                </td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>